### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Den-dp** [CanopyTax/single-spa-angular#118]
```
> jest
 FAIL  src/schematics/ng-add/index.spec.ts (5.174s)
  ng-add
    × should run ng-add (45ms)
    × should add single-spa dependency (1ms)
    × should add main-single-spa.ts (1ms)
    × should use correct prefix for root (1ms)
    × should not add router dependencies
    × should add router dependencies (1ms)
    × should modify angular.json (1ms)
    × should add build:single-spa npm script

  ● ng-add › should run ng-add

    Cannot find module 'C:\dev\single-spa-angular\lib\schematics\ng-add' from 'export-ref.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:202:17)
      at new ExportStringRef (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/export-ref.ts:19:28)
      at NodeModulesTestEngineHost._resolveReferenceString (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:121:17)
      at NodeModulesTestEngineHost.createSchematicDescription (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:235:30)
      at SchematicEngine.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:293:34)
      at CollectionImpl.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:90:25)
      at SchematicTestRunner.runSchematic (node_modules/@angular-devkit/schematics/testing/packages/angular_devkit/schematics/testing/schematic-test-runner.ts:93:40)

  ● ng-add › should add single-spa dependency

    Cannot find module 'C:\dev\single-spa-angular\lib\schematics\ng-add' from 'export-ref.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:202:17)
      at new ExportStringRef (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/export-ref.ts:19:28)
      at NodeModulesTestEngineHost._resolveReferenceString (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:121:17)
      at NodeModulesTestEngineHost.createSchematicDescription (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:235:30)
      at SchematicEngine.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:293:34)
      at CollectionImpl.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:90:25)
      at SchematicTestRunner.runSchematic (node_modules/@angular-devkit/schematics/testing/packages/angular_devkit/schematics/testing/schematic-test-runner.ts:93:40)

  ● ng-add › should add main-single-spa.ts

    Cannot find module 'C:\dev\single-spa-angular\lib\schematics\ng-add' from 'export-ref.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:202:17)
      at new ExportStringRef (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/export-ref.ts:19:28)
      at NodeModulesTestEngineHost._resolveReferenceString (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:121:17)
      at NodeModulesTestEngineHost.createSchematicDescription (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:235:30)
      at SchematicEngine.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:293:34)
      at CollectionImpl.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:90:25)
      at SchematicTestRunner.runSchematic (node_modules/@angular-devkit/schematics/testing/packages/angular_devkit/schematics/testing/schematic-test-runner.ts:93:40)

  ● ng-add › should use correct prefix for root

    Cannot find module 'C:\dev\single-spa-angular\lib\schematics\ng-add' from 'export-ref.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:202:17)
      at new ExportStringRef (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/export-ref.ts:19:28)
      at NodeModulesTestEngineHost._resolveReferenceString (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:121:17)
      at NodeModulesTestEngineHost.createSchematicDescription (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:235:30)
      at SchematicEngine.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:293:34)
      at CollectionImpl.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:90:25)
      at SchematicTestRunner.runSchematic (node_modules/@angular-devkit/schematics/testing/packages/angular_devkit/schematics/testing/schematic-test-runner.ts:93:40)

  ● ng-add › should not add router dependencies

    Cannot find module 'C:\dev\single-spa-angular\lib\schematics\ng-add' from 'export-ref.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:202:17)
      at new ExportStringRef (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/export-ref.ts:19:28)
      at NodeModulesTestEngineHost._resolveReferenceString (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:121:17)
      at NodeModulesTestEngineHost.createSchematicDescription (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:235:30)
      at SchematicEngine.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:293:34)
      at CollectionImpl.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:90:25)
      at SchematicTestRunner.runSchematic (node_modules/@angular-devkit/schematics/testing/packages/angular_devkit/schematics/testing/schematic-test-runner.ts:93:40)

  ● ng-add › should add router dependencies

    Cannot find module 'C:\dev\single-spa-angular\lib\schematics\ng-add' from 'export-ref.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:202:17)
      at new ExportStringRef (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/export-ref.ts:19:28)
      at NodeModulesTestEngineHost._resolveReferenceString (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:121:17)
      at NodeModulesTestEngineHost.createSchematicDescription (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:235:30)
      at SchematicEngine.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:293:34)
      at CollectionImpl.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:90:25)
      at SchematicTestRunner.runSchematic (node_modules/@angular-devkit/schematics/testing/packages/angular_devkit/schematics/testing/schematic-test-runner.ts:93:40)

  ● ng-add › should modify angular.json

    Cannot find module 'C:\dev\single-spa-angular\lib\schematics\ng-add' from 'export-ref.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:202:17)
      at new ExportStringRef (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/export-ref.ts:19:28)
      at NodeModulesTestEngineHost._resolveReferenceString (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:121:17)
      at NodeModulesTestEngineHost.createSchematicDescription (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:235:30)
      at SchematicEngine.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:293:34)
      at CollectionImpl.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:90:25)
      at SchematicTestRunner.runSchematic (node_modules/@angular-devkit/schematics/testing/packages/angular_devkit/schematics/testing/schematic-test-runner.ts:93:40)

  ● ng-add › should add build:single-spa npm script

    Cannot find module 'C:\dev\single-spa-angular\lib\schematics\ng-add' from 'export-ref.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:202:17)
      at new ExportStringRef (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/export-ref.ts:19:28)
      at NodeModulesTestEngineHost._resolveReferenceString (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/node-module-engine-host.ts:121:17)
      at NodeModulesTestEngineHost.createSchematicDescription (node_modules/@angular-devkit/schematics/tools/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts:235:30)
      at SchematicEngine.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:293:34)
      at CollectionImpl.createSchematic (node_modules/@angular-devkit/schematics/src/engine/packages/angular_devkit/schematics/src/engine/engine.ts:90:25)
      at SchematicTestRunner.runSchematic (node_modules/@angular-devkit/schematics/testing/packages/angular_devkit/schematics/testing/schematic-test-runner.ts:93:40)

Test Suites: 1 failed, 1 total
Tests:       8 failed, 8 total
Snapshots:   0 total
Time:        5.318s, estimated 6s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by joeldenning** [comment]
I confirmed this locally. I'd gladly review a PR for this. Also it would probably be good to add a Travis CI build for PRs that run the tests.

**Comment by joeldenning** [comment]
This occurs when you don't build before running the tests. Do the following and the tests work:

```sh
npm run build
npm test
```
